language: ruby
cache: bundler
sudo: false
rvm: 2.3.3

install: scripts/bootstrap
script: scripts/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
